# Continuous Integration

trigger:
  - main
pr: none

jobs:
  - job: npm
    displayName: Npm publish
    pool:
      vmImage: windows-2019
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 16.x
        displayName: Install Node.js

      - script: echo '##vso[task.setvariable variable=CADL_VS_CI_BUILD;]true'
        displayName: Enable official Visual Studio extension build

      - script: node common/scripts/install-run-rush.js install
        displayName: Install JavaScript Dependencies

      - script: node packages/cadl-vs/scripts/build.js --restore
        displayName: Restore .NET Dependencies

      - script: node common/scripts/install-run-rush.js rebuild --verbose
        displayName: Build

      - script: node common/scripts/install-run-rush.js test-official
        displayName: Test

      - template: ./upload-coverage.yml

      - script: |
          set NPM_AUTH_TOKEN=$(azure-sdk-npm-token)
          node common/scripts/install-run-rush.js publish --publish --include-all --set-access-level public
        displayName: Release

      - task: AzureFileCopy@4
        inputs:
          sourcePath: "packages/playground/dist/*"
          azureSubscription: "Azure SDK Playground"
          destination: "AzureBlob"
          storage: "cadlplayground"
          containerName: "$web"
        displayName: "Update playground"

  - job: docker
    displayName: Docker build and publish
    variables:
      imageName: "azsdkengsys.azurecr.io/cadl"
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@1
        displayName: login
        inputs:
          azureSubscriptionEndpoint: "AzureSDKEngKeyVault Secrets"
          azureContainerRegistry: azsdkengsys.azurecr.io
          command: login

      - script: |
          docker build -f ./docker/Dockerfile \
            -t $(imageName):latest \
            -t $(imageName):alpine \
            .
        displayName: "Build"

      - script: docker push $(imageName) --all-tags
        displayName: "Push"
